#!/bin/bash

if [[ -n $BLOCK_INSTANCE ]]; then
  IF=$BLOCK_INSTANCE
else
  IF=$(ip route | awk '/^default/ { print $5 ; exit }')
fi

[[ ! -d /sys/class/net/${IF} ]] && exit

#------------------------------------------------------------------------

if [[ ${BLOCK_BUTTON} -eq 1 ]]; then
  if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
    sudo ip link set $IF up
    sudo systemctl restart NetworkManager
  else
    sudo ip link set $IF down
  fi
fi

if [[ "$(cat /sys/class/net/$IF/operstate)" = 'down' ]]; then
  echo " off"
  echo " off"
  exit
fi

case $1 in
  -4)
    AF=inet ;;
  -6)
    AF=inet6 ;;
  *)
    AF=inet6? ;;
esac

IPADDR=$(ip addr show $IF | perl -n -e "/$AF ([^\/]+).* scope global/ && print \$1 and exit")

case $BLOCK_BUTTON in
  3) echo -n "$IPADDR" | xclip -q -se c ;;
esac

SSID_NAME=$(iwgetid -r)

device="${BLOCK_INSTANCE:-wlan0}"
status=$(cat /sys/class/net/${device}/operstate)

URGENT_VALUE=20

quality=100
if [[ "${status}" == "up" ]]; then
  quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
fi

INSTANCE="${BLOCK_INSTANCE}"
# If you don't like you can use any other IP
INTERFACE="$(ip route get 8.8.8.8 | grep -Po '(?<=(dev )).*(?= src)')"

if [[ "${INSTANCE}" = "" ]]; then
  INSTANCE="${INTERFACE};both"
fi

INSTANCE=$(echo "${INSTANCE}" | awk -F ';' '{print $1}')

ONE_KB=1
ONE_MB=$(echo "${ONE_KB}*1024" | bc -l)
TEN_MB=$(echo "${ONE_MB}*10" | bc -l)
OHD_MB=$(echo "${TEN_MB}*10" | bc -l)

BYTES=$(sar -n DEV 1 1 | grep wlp3s0 | grep Average)
BYTES_OUT=$(echo $BYTES | awk '{ print $4 }' | bc -l)
BYTES_IN=$(echo $BYTES | awk '{ print $5 }' | bc -l)

function FormatNumber() {
  if [[ "$(echo ${1%.*})" -ge "${OHD_MB}" ]]; then
    echo $(echo "scale=0;${1}/${ONE_MB}" | bc -l)"M/S"
  elif [[ "$(echo ${1%.*})" -ge "${TEN_MB}" ]]; then
    echo $(echo "scale=1;${1}/${ONE_MB}" | bc -l)"M/S"
  elif [[ "$(echo ${1%.*})" -ge "${ONE_MB}" ]]; then
    echo $(echo "scale=2;${1}/${ONE_MB}" | bc -l)"M/S"
  elif [[ "$(echo ${1%.*})" -ge "${ONE_KB}" ]]; then
    echo ${1}"K/S"
  else
    echo $(echo "${1}*1024" | bc -l)"B/S"
  fi
}

if [[ "${BYTES_IN}" != "" ]] && [[ "${BYTES_OUT}" != "" ]]; then
  USAGE_IN=$(FormatNumber "${BYTES_IN}")
  USAGE_OUT=$(FormatNumber "${BYTES_OUT}")
fi

if [[ "${SSID_NAME}" != "" ]]; then
  echo "[${quality}%][${SSID_NAME}][$IPADDR] ${USAGE_OUT}  ${USAGE_IN}" # full text
  echo "[${quality}%][${SSID_NAME}][$IPADDR] ${USAGE_OUT}  ${USAGE_IN}" # full text
fi

if [[ "${quality}" -le "${URGENT_VALUE}" ]]; then
  exit 33
fi

